---
- name: Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.31.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
