name: Create Stack

on:
  workflow_dispatch:  

permissions:
  contents: read

jobs:
  create:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION
        
    - name: Create ~/.ssh Directory and Add Public Key
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub
        
    - name: Run state bucket creation script
      run: |
        cd terraform
        chmod +x create-state-bucket.sh
        ./create-state-bucket.sh  

    - name: Run Terraform Apply
      run: |
        cd terraform
        terraform init 
        terraform apply -auto-approve
